[package]
authors = ["peauters <40306785+peauters@users.noreply.github.com>"]
name = "peautkb"
edition = "2018"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.6.13"
defmt = "0.2.0"
defmt-rtt = "0.2.0"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }
stm32f4 = "0.11"
cortex-m-rtic = "0.6.0-alpha.2"
dwt-systick-monotonic = "0.1.0-alpha.1"
usb-device = "0.2.8"
keyberon = { git = "https://github.com/TeXitoi/keyberon" }
embedded-graphics = "0.6.2"
ssd1306 = "0.5.1"
embedded-hal = "0.2.4"
ws2812-spi = "0.4.0"
smart-leds = "0.3.0"
nb = "1.0.0"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
postcard = "0.6.1"
heapless = "0.6.1"
generic-array = "0.14"
numtoa = "0.2.3"
embedded-dma = "0.1.2"


[dependencies.stm32f4xx-hal]
# path = "../../../rust/stm32f4xx-hal"
version = "0.9.0"
features = ["stm32f411", "rt", "usb_fs"]

[dev-dependencies]
panic-halt = "0.2.0"

[features]
# set logging levels here
default = ["defmt-default"] # "dependency-a/defmt-trace",


# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

# cargo build/run
[profile.dev]
# codegen-units = 1
# debug = 2
# debug-assertions = true # <-
# incremental = false
# # lto = true
# # opt-level = 'z' # <-
overflow-checks = false # <-

# cargo build/run --release
[profile.release]
# codegen-units = 1
debug = 2
# debug-assertions = false # <-
# incremental = false
# lto = true
# opt-level = 'z' # <-
overflow-checks = true # <-

[[example]]
name = "dma"

[[example]]
name = "leds"
